# Generated by Django 4.1.7 on 2023-09-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejectes', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
